Feat/#5
AegisLenz/AegisLenz-PE pull request #6
Opened 2024-10-28 11:10 UTC by shinyeji-spea

## 🔥 Related Issue
- Close #5 

## 🏃‍ Task
- 분류기 단일값 반환 구현
- 페르소나 로직 수정 

## 💬 To Reviews 
- 분류기는 이제 단일값으로 나옵니다!
- ES, MongoDB, Policy 다음에 대시보드 프롬프트도 호출하도록 됐습니다!
- 비동기 처리는 '로직부분' 좀 더 생각해보고 진행 예정입니다!

## 📄 Reference
- None

## ✅ Check List
- [ ]  PR의 제목은 팀 내 규칙을 준수하여 알맞게 작성하였는가?
- [ ]  Merge 하는 브랜치가 올바른가? (`main` branch에 실수로 PR 생성 금지)
- [ ]  팀의 코딩 컨벤션을 준수하는가?
- [ ]  PR과 관련없는 변경사항이 들어가지는 않았는가?
- [ ]  내 코드에 대한 자기 검토가 되었는가?
- [ ]  Reviewers, Assignees, Lables, Project, Milestone은 적절하게 선택하였는가?
- [ ]  관련한 issue를 닫아야 하는지 점검해보고 적용했는가?

2024-10-28 11:25 UTC, jyjyjy25 requested changes
Bob

2024-10-28 11:28 UTC, breakpack requested changes
화이티잉

2024-10-28 11:28 UTC, breakpack commented on NowPrompt/Engineering/ClassifyPr.txt
> +응답을 JSON 형식으로 반환하되, 'topics' 배열에 **오직 하나의 값만 포함**해 주세요. 배열에 하나 이상의 값이 포함되지 않도록 합니다. 예시: { 'topics': ['필요한 단일 값'] }
단일값을 하는 이유를 모르겠어요.. 두개를 동시에 조회해야하는 질문은 어떻게 해요..

Ex) 일주일 동안 접속하지 않은 유저와 이 유저의 마지막 활동 로그를 보고 싶어.

2024-10-28 11:28 UTC, breakpack commented on NowPrompt/testapi.py
>              # 히스토리 관리 (최대 10개 유지)
갯수에 따라 파일을 구분하는게 아니라 한 세션에 대해서 한 개의 파일을 사용해야 할 것 같아요

2024-10-28 11:28 UTC, breakpack commented on history_Dash.txt
> +system: 당신은 우리 서비스에서 조회할 내용을 결정하는 전문가입니다.
History에 프롬프트 엔지니어링 내용은 안넣어도 될 것 같아요

넣을 거면 사용자한테 제공할 내용을 저장하는 히스토리 파일도 별개로 사용해야 할 것 같아요

2024-10-29 05:29 UTC, shinyeji-spea commented on history_Dash.txt
> +system: 당신은 우리 서비스에서 조회할 내용을 결정하는 전문가입니다.
해당 history 파일들은 **for 문을 돌면서 쌓인 질문**, **응답**을 넣어 예시를 제공함으로써 **Few-shot Prompting** 기술을 사용하는 것입니다.

2024-10-29 05:29 UTC, shinyeji-spea commented on NowPrompt/testapi.py
>              # 히스토리 관리 (최대 10개 유지)
백엔드에서 이미 구현돼 있어서 넘어갔습니다.

2024-10-29 11:06 UTC, shinyeji-spea commented on NowPrompt/Engineering/ClassifyPr.txt
> +응답을 JSON 형식으로 반환하되, 'topics' 배열에 **오직 하나의 값만 포함**해 주세요. 배열에 하나 이상의 값이 포함되지 않도록 합니다. 예시: { 'topics': ['필요한 단일 값'] }
단일 값부터 구현하고 추후 두 개 동시 조회 질문 구현 예정입니다.

2024-10-29 11:07 UTC, shinyeji-spea commented on NowPrompt/testapi.py
>          for classification_result in classification_results:
for문 제거했습니다.

2024-10-29 11:07 UTC, shinyeji-spea commented on NowPrompt/testapi.py
> +        classification_results = classify_data.get("topics", []) # 'topics'에 여러 분류 값이 포함됨
처리했습니다.

2024-10-29 11:08 UTC, shinyeji-spea commented on NowPrompt/testapi.py
>              # 분류 결과에 따른 프롬프트 설정
통일 완료 했습니다.

2024-10-30 05:20 UTC, jyjyjy25 approved these changes
LGTM

2024-10-30 05:20 UTC, jyjyjy25 commented on NowPrompt/Engineering/ClassifyPr.txt
> +주제는 "Dash", "ES", "DB", "policy"가 있습니다.
policy도 Policy로 수정 가능할까요

2024-10-30 05:21 UTC, breakpack approved these changes

2024-10-30 06:11 UTC, merged